
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrateur_Aly
 */
public class Amis extends javax.swing.JPanel {

    /**
     * Creates new form Amis
     */
    public Amis() {
        initComponents();
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Prenom");
        model.addColumn("Nom");
        model.addColumn("adresse");
        model.addColumn("telephone");
        model.addColumn("mail");
        model.addColumn("Nom_Master");
         model.addColumn("Niveau_master");
        model.addColumn("Poste");
        model.addColumn("Entreprise");
         table.setModel(model);
         affiche_amis();
    }
    public ArrayList<Liste_amis> listeamis(){
       ArrayList<Liste_amis> listeamis =new ArrayList<>();
       try{
            Connection con = Connexion.getCo();
            String req1="SELECT *from etudiant,emploi where etudiant.id_etu=emploi.id_emploi " ;
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(req1);
            Liste_amis amis;
            while(rs.next()){
                amis =new Liste_amis(rs.getString("prenom"),rs.getString("nom"),rs.getString("adresse"),rs.getLong("telephone"),rs.getString("mail"),rs.getString("nom_master"),rs.getString("niveau_master"),rs.getString("nom_poste"),rs.getString("entreprise"));
                listeamis.add(amis);
            }
       }
       catch(Exception e){
            JOptionPane.showMessageDialog( null, e);
        }
       return listeamis;
    }
    public void affiche_amis(){
        ArrayList<Liste_amis> list=listeamis();
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        Object[] row=new Object[9];
        for(int i=0;i<list.size();i++){
             row[0]=list.get(i).getprenom();
             row[1]=list.get(i).getnom();
              row[2]=list.get(i).getadresse();
               row[3]=list.get(i).gettelephone();
                row[4]=list.get(i).getmail();
                row[5]=list.get(i).getnom_master();
                row[6]=list.get(i).getniveau_master();
                 row[7]=list.get(i).getnom_poste();
               row[8]=list.get(i).getentreprise();
          
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amis", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 48), new java.awt.Color(255, 204, 204)))); // NOI18N

        table.setBackground(new java.awt.Color(204, 255, 204));
        table.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""))));
        table.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(102, 153, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
