
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrateur_Aly
 */
public class Gestion_Salle extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Gestion_Salle() {
        initComponents();
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("id_salles");
        model.addColumn("nom_salle");
        model.addColumn("places");
        model.addColumn("projectable");
        model.addColumn("acces_handicape");
        model.addColumn("etat");
        liste.setModel(model);
        affiche_salle();
    }
    public ArrayList<Classe> listeClasse(){
       ArrayList<Classe> listeClasse =new ArrayList<>();
       try{
            Connection con = Connexion.getCo();
            String req1="SELECT *FROM salles";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(req1);
            Classe classe;
            while(rs.next()){
                classe =new Classe(rs.getInt("id_salles"),rs.getString("nom_salle"),rs.getInt("places"),rs.getString("projectable"),rs.getString("acces_handicape"),rs.getString("etat"));
                listeClasse.add(classe);
            }
       }
       catch(Exception e){
            JOptionPane.showMessageDialog( null, e);
        }
       return listeClasse;
    }
    public void affiche_salle(){
        ArrayList<Classe> list=listeClasse();
        DefaultTableModel model=(DefaultTableModel)liste.getModel();
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++){
             row[0]=list.get(i).getid_salles();
             row[1]=list.get(i).getnom_salle();
             row[2]=list.get(i).getplaces();
              row[3]=list.get(i).getprojectable();
               row[4]=list.get(i).getacces_handicape();
                row[5]=list.get(i).getetat();
                
      
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        liste = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ajout = new javax.swing.JButton();
        modif = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        id_sal = new javax.swing.JLabel();
        no_sal = new javax.swing.JLabel();
        plac = new javax.swing.JLabel();
        pro = new javax.swing.JLabel();
        ac_han = new javax.swing.JLabel();
        eta = new javax.swing.JLabel();
        nom_salle = new javax.swing.JTextField();
        places = new javax.swing.JTextField();
        id_salles = new javax.swing.JTextField();
        etat = new javax.swing.JComboBox();
        projectable = new javax.swing.JComboBox();
        acces_handicape = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 0));
        setPreferredSize(new java.awt.Dimension(1252, 430));

        liste.setBackground(new java.awt.Color(204, 153, 255));
        liste.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_salles", "nom_salle", "places", "projectable", "acces_handicape", "etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(liste);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""))));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ajout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ajout.setText("AJOUTER");
        ajout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });

        modif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modif.setText("MODIFIER");
        modif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt);
            }
        });

        supprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supprimer.setText("SUPPRIMER");
        supprimer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Information Personnelles")));
        jPanel3.setForeground(new java.awt.Color(0, 51, 153));

        id_sal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id_sal.setForeground(new java.awt.Color(0, 51, 153));
        id_sal.setText("id_salles:");

        no_sal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        no_sal.setForeground(new java.awt.Color(0, 51, 153));
        no_sal.setText("nom_salle");

        plac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plac.setForeground(new java.awt.Color(0, 51, 153));
        plac.setText("places");

        pro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pro.setForeground(new java.awt.Color(0, 51, 153));
        pro.setText("projectable");

        ac_han.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ac_han.setForeground(new java.awt.Color(0, 51, 153));
        ac_han.setText("acces_handicape");

        eta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eta.setForeground(new java.awt.Color(0, 51, 153));
        eta.setText("etat");

        nom_salle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_salleActionPerformed(evt);
            }
        });

        places.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placesActionPerformed(evt);
            }
        });

        id_salles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_sallesActionPerformed(evt);
            }
        });
        id_salles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_sallesKeyTyped(evt);
            }
        });

        etat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "occupee", "libre", " ", " " }));
        etat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etatActionPerformed(evt);
            }
        });

        projectable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non" }));

        acces_handicape.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oui", "non", " " }));
        acces_handicape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acces_handicapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_sal)
                    .addComponent(pro)
                    .addComponent(eta)
                    .addComponent(ac_han, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(plac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(no_sal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(projectable, javax.swing.GroupLayout.Alignment.TRAILING, 0, 130, Short.MAX_VALUE)
                        .addComponent(places, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nom_salle, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(id_salles, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(etat, javax.swing.GroupLayout.Alignment.TRAILING, 0, 130, Short.MAX_VALUE)
                        .addComponent(acces_handicape, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_sal)
                    .addComponent(id_salles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_sal)
                    .addComponent(nom_salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plac)
                    .addComponent(places, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pro)
                    .addComponent(projectable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ac_han)
                    .addComponent(acces_handicape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eta)
                    .addComponent(etat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("                                                                                        GESTION DE SALLES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void id_sallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_sallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_sallesActionPerformed

    private void id_sallesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_sallesKeyTyped
        // TODO add your handling code here:
       // if(!Character.isDigit(evt.getKeyChar())){
       // evt.consume();}
    }//GEN-LAST:event_id_sallesKeyTyped

    private void placesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placesActionPerformed

    private void listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeMouseClicked
        // TODO add your handling code here:
         int i = liste.getSelectedRow();
        TableModel model = liste.getModel();
        id_salles.setText(model.getValueAt(i, 0).toString());
        nom_salle.setText(model.getValueAt(i, 1).toString());
        places.setText(model.getValueAt(i, 2).toString());
        projectable.setSelectedItem(model.getValueAt(i, 3).toString());
        acces_handicape.setSelectedItem(model.getValueAt(i, 4).toString());
     
        etat.setSelectedItem(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_listeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Gestion des salles");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            liste.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            

        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impression ", e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void acces_handicapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acces_handicapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acces_handicapeActionPerformed

    private void etatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etatActionPerformed

    private void nom_salleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_salleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_salleActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
    
        try{
          Connection con = Connexion.getCo();
            String query="insert into salles(nom_salle,places,projectable,acces_handicape,etat) VALUES(?,?,?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(query);
          pst.setString(1, nom_salle.getText());
          pst.setString(2,places.getText());
          pst.setString(3,projectable.getSelectedItem().toString());
          pst.setString(4,acces_handicape.getSelectedItem().toString());
          pst.setString(5,etat.getSelectedItem().toString());
          System.out.println(etat.getSelectedItem().toString());
          pst.executeUpdate();
           DefaultTableModel model=(DefaultTableModel)liste.getModel();
          model.setRowCount(0);
          affiche_salle();
       JOptionPane.showMessageDialog(null,"Salle bien ajouter");
       setfields();
         AccueilAdministrateur.Text.setText("Bien inseré dans la base");
            }
       catch(Exception e){
          JOptionPane.showMessageDialog( null, e);
           AccueilAdministrateur.Text.setText("erreur");
       } 
    }//GEN-LAST:event_ajoutActionPerformed

     private void setfields() {
        nom_salle.setText(null);                        //pour vider la table
        places.setText(null);
        projectable.setSelectedItem(null);
        acces_handicape.setSelectedItem(null);
        etat.setSelectedItem(null);
    }
    
    
    private void modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifActionPerformed
       int i = liste.getSelectedRow();
           TableModel model = liste.getModel();
           String id_sal = model.getValueAt(i, 0).toString();        //Pour recuperer l'Id_salle
           int id_s = Integer.parseInt(id_sal);
           
           try{
            Connection con = Connexion.getCo();
            String query="UPDATE salles SET nom_salle = ?, places = ?, projectable = ?, acces_handicape = ?, etat = ? WHERE id_salles = ?";            
            PreparedStatement pst = con.prepareStatement(query);
            
            
            pst.setString(1, nom_salle.getText());             
            pst.setString(2, places.getText());          
            pst.setString(3,projectable.getSelectedItem().toString());
            pst.setString(4,acces_handicape.getSelectedItem().toString());
            pst.setString(5,etat.getSelectedItem().toString());
            pst.setInt(6, id_s);
            
            pst.executeUpdate();
         
           DefaultTableModel modele=(DefaultTableModel)liste.getModel();    
           modele.setRowCount(0);
          
          affiche_salle();
          
       JOptionPane.showMessageDialog(null,"Modification effectué");
       setfields();
        
         AccueilAdministrateur.Text.setText("Modification reussie");
            }
       catch(Exception e){
          JOptionPane.showMessageDialog( null, e);
           AccueilAdministrateur.Text.setText("erreur");
       }                   
    
    }//GEN-LAST:event_modifActionPerformed

    
    
    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        int i = liste.getSelectedRow();
           TableModel model = liste.getModel();
           String id_per = model.getValueAt(i, 0).toString();
           int id_p = Integer.parseInt(id_per);
           
          
          
        int dialogButton = JOptionPane.YES_NO_OPTION;
       JOptionPane.showConfirmDialog(null, "Voulez vous vraiment supprimer cette personne");
       if (dialogButton == JOptionPane.YES_OPTION)
       {        
     try      
       {
           
           Connection con = Connexion.getCo();
           String requete = "DELETE FROM salles WHERE id_salles=?";
           
           PreparedStatement pst = con.prepareStatement(requete);                                           
           pst.setInt(1, id_p);                      
           pst.executeUpdate();
           
            DefaultTableModel mod = (DefaultTableModel)liste.getModel();  //pour mettre a jour la table
           mod.removeRow(liste.getSelectedRow());
           
           //affiche_salle();
           JOptionPane.showMessageDialog(null,"Suppression effectué"); 
           
       }
     
     catch(Exception e){ 
           JOptionPane.showMessageDialog( null, e);
           AccueilAdministrateur.Text.setText("erreur");  } 
       
       }
       else
         if (dialogButton == JOptionPane.NO_OPTION)  
         {JOptionPane.showMessageDialog(null,"Suppression annuler"); }
    }//GEN-LAST:event_supprimerActionPerformed
    
    
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilAdministrateur().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ac_han;
    private javax.swing.JComboBox acces_handicape;
    private javax.swing.JButton ajout;
    private javax.swing.JLabel eta;
    private javax.swing.JComboBox etat;
    private javax.swing.JLabel id_sal;
    private javax.swing.JTextField id_salles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable liste;
    private javax.swing.JButton modif;
    private javax.swing.JLabel no_sal;
    private javax.swing.JTextField nom_salle;
    private javax.swing.JLabel plac;
    private javax.swing.JTextField places;
    private javax.swing.JLabel pro;
    private javax.swing.JComboBox projectable;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
